Numpy ndarray 개요

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]
print("list1:", list1)
print("list1 type:", type(list1))

array1 =np.array(list1)
print("arrat1:", array1)
print("array1 type:", type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
arrat1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


In [3]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [8]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


In [10]:
list2 = [1,2,'HAN DONG HUN']
array2 = np.array(list2) #정수값이 더 큰 문자형 값으로 변형된다.
print(array2, array2.dtype)

list3 = [1,2,5.7]
array3 = np.array(list3) #모두 실수 형태인 float으로 변형된다.
print(array3, array3.dtype)

['1' '2' 'HAN DONG HUN'] <U12
[1.  2.  5.7] float64


In [13]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') #변화시켜주고자 하는 데이터 타입을 'float64를 입력'
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32') #float형태를 다시 int형태로 바꾸어줘보자
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float.astype('int32')  #실수형태인데 int로 바꿔주라고 해서 바꿔졌네.. 신기하네..
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


 * ndarray에서 axis 기반의 연산함수 수행

In [15]:
array2 = np.array([[1,2,3],[2,3,4]])
#[1,2,3]
#[2,3,4]
print(array2.sum())
print(array2.sum(axis=0)) #세로인 열 방향
print(array2.sum(axis=1)) #가로인 행 방향

15
[3 5 7]
[6 9]
